project_id = "zybdotagjwektucfdkri"

[functions.notify-version-update]
verify_jwt = false

[functions.check-compatibility-status]
verify_jwt = false

[functions.create-split-checkout-session]
verify_jwt = false

[functions.create-pwyw-checkout-session]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.import-github-readme]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.seed-new-posts]
verify_jwt = false

[functions.post-json]
verify_jwt = false

[functions.sitemap-xml]
verify_jwt = false